// DEFINE PREFIX TO USE FOR METHODS NAME FOR MAKE LIFE EASIER

// PORTFOLIO => PREFIX => 1
// PORTFOLIO - ACTIONS
export const SELL_STOCK_A1 = 'PORTFOLIO_SELL_STOCK_ACTION';

// PORTFOLIO - MUTATIONS
export const BUY_STOCK_M1 = 'PORTFOLIO_BUY_STOCK_MUTATION';
export const SELL_STOCK_M1 = 'PORTFOLIO_SELL_STOCK_MUTATION';

// PORTFOLIO - GETTERS
export const GET_STOCKS_G1 = 'PORTFOLIO_GET_STOCKS_GETTERS';
export const GET_FUNDS_G1 = 'PORTFOLIO_GET_FUNDS_GETTERS';

// STOCKS => PREFIX => 2
// STOCKS - ACTIONS
export const INIT_STOCKS_A2 = 'STOCKS_INIT_STOCKS_ACTION';
export const BUY_STOCK_A2 = 'STOCKS_BUY_STOCK_ACTION';
export const RND_STOCKS_A2 = 'STOCKS_RND_STOCKS_ACTION';

// STOCKS - MUTATIONS
export const SET_STOCKS_M2 = 'STOCKS_SET_STOCKS_MUTATION';
export const RND_STOCKS_M2 = 'STOCKS_RND_STOCKS_MUTATION';

// STOCKS - GETTERS
export const GET_STOCKS_G2 = 'STOCKS_GET_STOCKS_GETTERS';
